### ISSUE TITLE
error with AH2 - v1.0.7

### ISSUE THREAD

**Issue by jsmdy** [jurialmunkey/script.skinvariables#19]
I've got this error since a fresh  W10 install, I used the save extension on kodi to keep maximum data of previous config. 

The error happened only when I click on tv show poster  to detail the episodes, the episode page is empty
no problems with movie/tc show informations, nor launching movies.

The message on Kodi prompting on screen info 'Skin variable error' : 

_2022-12-05 15:39:47.108 T:10664    INFO <general>: initializing python engine.
2022-12-05 15:39:47.108 T:10664   DEBUG <general>: CPythonInvoker(36, C:\Users\jsmon\AppData\Roaming\Kodi\addons\script.skinvariables\script.py): start processing
2022-12-05 15:39:47.119 T:10600   DEBUG <general>: Thread BackgroundLoader 10600 terminating
2022-12-05 15:39:47.151 T:10664   DEBUG <general>: -->Python Interpreter Initialized<--
2022-12-05 15:39:47.151 T:10664   DEBUG <general>: 
                                                   
2022-12-05 15:39:47.151 T:10664   DEBUG <general>: CPythonInvoker(36, C:\Users\jsmon\AppData\Roaming\Kodi\addons\script.skinvariables\script.py): the source file to load is "C:\Users\jsmon\AppData\Roaming\Kodi\addons\script.skinvariables\script.py"
2022-12-05 15:39:47.151 T:10664   DEBUG <general>: CPythonInvoker(36, C:\Users\jsmon\AppData\Roaming\Kodi\addons\script.skinvariables\script.py): setting the Python path to C:\Users\jsmon\AppData\Roaming\Kodi\addons\script.skinvariables;C:\Users\jsmon\AppData\Roaming\Kodi\addons\script.module.tmdbhelper\resources\modules;C:\Program Files\Kodi\system\python\Lib;C:\Program Files\Kodi\python3.8.zip;C:\Program Files\Kodi\system\python\DLLs;C:\Program Files\Kodi;C:\Program Files\Kodi\system\python;C:\Program Files\Kodi\system\python\lib\site-packages
2022-12-05 15:39:47.151 T:10664   DEBUG <general>: CPythonInvoker(36, C:\Users\jsmon\AppData\Roaming\Kodi\addons\script.skinvariables\script.py): entering source directory C:\Users\jsmon\AppData\Roaming\Kodi\addons\script.skinvariables
2022-12-05 15:39:47.152 T:10664   DEBUG <general>: CPythonInvoker(36, C:\Users\jsmon\AppData\Roaming\Kodi\addons\script.skinvariables\script.py): instantiating addon using automatically obtained id of "script.skinvariables" dependent on version 3.0.0 of the xbmc.python api
2022-12-05 15:39:47.264 T:10664   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'json.decoder.JSONDecodeError'>
                                                   Error Contents: Expecting value: line 1 column 1 (char 0)
                                                   Traceback (most recent call last):
                                                     File "C:\Users\jsmon\AppData\Roaming\Kodi\addons\script.skinvariables\script.py", line 8, in <module>
                                                       Script().run()
                                                     File "C:\Users\jsmon\AppData\Roaming\Kodi\addons\script.skinvariables\resources\lib\script.py", line 47, in run
                                                       return self.router()
                                                     File "C:\Users\jsmon\AppData\Roaming\Kodi\addons\script.skinvariables\resources\lib\script.py", line 53, in router
                                                       return ViewTypes().update_xml(skinfolder=self.params.get('folder'), **self.params)
                                                     File "C:\Users\jsmon\AppData\Roaming\Kodi\addons\script.skinvariables\resources\lib\viewtypes.py", line 41, in __init__
                                                       self.addon_meta = loads(self.addon_content) or {} if self.addon_content else {}
                                                     File "C:\Program Files\Kodi\system\python\Lib\json\__init__.py", line 357, in loads
                                                       return _default_decoder.decode(s)
                                                     File "C:\Program Files\Kodi\system\python\Lib\json\decoder.py", line 337, in decode
                                                       obj, end = self.raw_decode(s, idx=_w(s, 0).end())
                                                     File "C:\Program Files\Kodi\system\python\Lib\json\decoder.py", line 355, in raw_decode
                                                       raise JSONDecodeError("Expecting value", s, err.value) from None
                                                   json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
                                                   -->End of Python script error report<--
                                                   
2022-12-05 15:39:47.264 T:10664   DEBUG <general>: CPythonInvoker::onExecutionDone(36, C:\Users\jsmon\AppData\Roaming\Kodi\addons\script.skinvariables\script.py)
2022-12-05 15:39:47.268 T:11588   DEBUG <general>: ------ Window Init (DialogNotification.xml) ------
2022-12-05 15:39:47.641 T:10664    INFO <general>: Python interpreter stopped_

**Comment by jsmdy** [comment]
I clean the database, rescan fully the tv show (windows change the HDD letter, so I lost the TV show infos, that's why I rescan the tv show folder).
I also reinstall and old version of the extension and made an update to tried to have a clean install of the extension.

**Comment by jurialmunkey** [comment]
Upload full log. No snippets as I can't read that mess of unformatted text.

Either upload to a paste site like https://paste.kodi.tv/ and copy link here, or put in a zip and upload to a github comment.

**Comment by jsmdy** [comment]
-deleted-

**Comment by jurialmunkey** [comment]
Your viewtypes file is corrupted. Likely wasn't copied over correctly. 

Delete the file and skinvariables will rebuild a new one:
`%APPDATA%/Kodi/userdata/addon_data/script.skinvariables/skin.arctic.horizon.2-viewtypes.json`

**Comment by jsmdy** [comment]
works perfectly now, thank you 👍 .
