### ISSUE TITLE
[Matrix] Add-on errors out with json.decoder.JSONDecodeError

### ISSUE THREAD

**Issue by ghost** [jurialmunkey/script.skinvariables#7]
After installing Arctic Horizon I am getting errors on almost every screen. Also can't change the view from list to poster etc. for example. Kodi.log shows the following:

```
2021-02-25 17:44:11.879 T:6473    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'json.decoder.JSONDecodeError'>
                                                   Error Contents: Expecting value: line 1 column 1 (char 0)
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.skinvariables/script.py", line 10, in <module>
                                                       TMDbScript.router()
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.skinvariables/resources/lib/script.py", line 129, in router
                                                       self.make_variables()
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.skinvariables/resources/lib/script.py", line 37, in make_variables
                                                       meta = loads(content) or []
                                                     File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.8/lib/python3.8/json/__init__.py", line 357, in loads
                                                       return _default_decoder.decode(s)
                                                     File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.8/lib/python3.8/json/decoder.py", line 337, in decode
                                                       obj, end = self.raw_decode(s, idx=_w(s, 0).end())
                                                     File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.8/lib/python3.8/json/decoder.py", line 355, in raw_decode
                                                       raise JSONDecodeError("Expecting value", s, err.value) from None
                                                   json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
                                                   -->End of Python script error report<--
```

**Comment by ghost** [comment]
Never mind, it did not take your version off the repo but the default one :)
