### ISSUE TITLE
This addon does not work in the matrix version.

### ISSUE THREAD

**Issue by taxdriver4u** [jurialmunkey/script.skinvariables#9]
If you run it after installation in the matrix version, an error occurs.

**Comment by drinfernoo** [comment]
Update to the latest version from the repo.

**Comment by jurialmunkey** [comment]
Debug Log?

Matrix version works completely fine for me.

**Comment by taxdriver4u** [comment]
> Debug Log?
> 
> Matrix version works completely fine for me.

2021-04-28 12:59:01.277 T:1284     INFO <general>: initializing python engine.
2021-04-28 12:59:01.355 T:1284    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'json.decoder.JSONDecodeError'>
                                                   Error Contents: Expecting value: line 1 column 1 (char 0)
                                                   Traceback (most recent call last):
                                                     File "C:\Users\ceo\AppData\Roaming\Kodi\addons\script.skinvariables\script.py", line 10, in <module>
                                                       TMDbScript.router()
                                                     File "C:\Users\ceo\AppData\Roaming\Kodi\addons\script.skinvariables\resources\lib\script.py", line 36, in router
                                                       SkinVariables().update_xml(
                                                     File "C:\Users\ceo\AppData\Roaming\Kodi\addons\script.skinvariables\resources\lib\skinvariables.py", line 20, in __init__
                                                       self.meta = loads(self.content) or []
                                                     File "C:\Program Files\Kodi\system\python\Lib\json\__init__.py", line 357, in loads
                                                       return _default_decoder.decode(s)
                                                     File "C:\Program Files\Kodi\system\python\Lib\json\decoder.py", line 337, in decode
                                                       obj, end = self.raw_decode(s, idx=_w(s, 0).end())
                                                     File "C:\Program Files\Kodi\system\python\Lib\json\decoder.py", line 355, in raw_decode
                                                       raise JSONDecodeError("Expecting value", s, err.value) from None
                                                   json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
                                                   -->End of Python script error report<--
                                                   
2021-04-28 12:59:01.359 T:15472    INFO <general>: CActiveAESink::OpenSink - initialize sink
2021-04-28 12:59:01.390 T:1284     INFO <general>: Python interpreter stopped

**Comment by jurialmunkey** [comment]
Full debug log please. No snippets.

Please upload the log to https://paste.kodi.tv/ and give the link rather than copy pasting text here.

**Comment by taxdriver4u** [comment]
Sorry.
I misunderstood how to use it.
I solved it.
Thank you.
